services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    networks:
      - network

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    volumes:
      - ./api:/app
    networks:
      - network

  websocket:
    build:
      context: ./websocket
      dockerfile: ../docker/websocket/Dockerfile
    volumes:
      - ./websocket:/app
    networks:
      - network
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $}MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - network
networks:
  network: